package life.usc.study.model;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN.ID
     *
     * @mbg.generated Tue May 19 15:30:57 PDT 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN.NAME
     *
     * @mbg.generated Tue May 19 15:30:57 PDT 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN.PASSWORD
     *
     * @mbg.generated Tue May 19 15:30:57 PDT 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN.NICK_NAME
     *
     * @mbg.generated Tue May 19 15:30:57 PDT 2020
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN.LOCKED
     *
     * @mbg.generated Tue May 19 15:30:57 PDT 2020
     */
    private Integer locked;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN.ID
     *
     * @return the value of ADMIN.ID
     *
     * @mbg.generated Tue May 19 15:30:57 PDT 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN.ID
     *
     * @param id the value for ADMIN.ID
     *
     * @mbg.generated Tue May 19 15:30:57 PDT 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN.NAME
     *
     * @return the value of ADMIN.NAME
     *
     * @mbg.generated Tue May 19 15:30:57 PDT 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN.NAME
     *
     * @param name the value for ADMIN.NAME
     *
     * @mbg.generated Tue May 19 15:30:57 PDT 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN.PASSWORD
     *
     * @return the value of ADMIN.PASSWORD
     *
     * @mbg.generated Tue May 19 15:30:57 PDT 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN.PASSWORD
     *
     * @param password the value for ADMIN.PASSWORD
     *
     * @mbg.generated Tue May 19 15:30:57 PDT 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN.NICK_NAME
     *
     * @return the value of ADMIN.NICK_NAME
     *
     * @mbg.generated Tue May 19 15:30:57 PDT 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN.NICK_NAME
     *
     * @param nickName the value for ADMIN.NICK_NAME
     *
     * @mbg.generated Tue May 19 15:30:57 PDT 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN.LOCKED
     *
     * @return the value of ADMIN.LOCKED
     *
     * @mbg.generated Tue May 19 15:30:57 PDT 2020
     */
    public Integer getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN.LOCKED
     *
     * @param locked the value for ADMIN.LOCKED
     *
     * @mbg.generated Tue May 19 15:30:57 PDT 2020
     */
    public void setLocked(Integer locked) {
        this.locked = locked;
    }
}